### ISSUE TITLE
Can't pass user data to module. String Required

### ISSUE THREAD

**Issue by tkennedy-cf** [Coalfire-CF/terraform-aws-ec2#16]
**Describe the bug**
Using the user data code in the `README.md` I am attempting to pass user data to the EC2 instance but receive the following error:

![image](https://github.com/Coalfire-CF/terraform-aws-ec2/assets/101284566/e14dc969-d04b-4ffc-8d6d-054abc1ddc37)

**To Reproduce**
1. Copy the user data code and pass the `user_data` code.
```terraform
user_data = [
    {
      path = {
        folder_name = "linux",
        file_name   = "test.sh"
      }
      vars = {
        test-var1 = "test1",
        test-var2 = "test2"
      }
    }
  ]

```
3. Run `terraform init` and the `terraform validate` 

**Expected behavior**
I expected to the module to handle the user data I passed

**Screenshots**
Attached

**Additional recommendations**
Upon fixing the user data module please update the supporting `README.md` and example code

**Comment by kourosh-forti-hands** [comment]
was any troubleshooting attempted @tkennedy-cf ?

**Comment by herman-wong-cf** [comment]
User data is expected to be a "string" and not a "list of maps".  The provided example is not valid as we previously needed to do a hack (by modifying Amazon system files) on the Windows AMI to allow it to process multiple user data scripts.  This modification put it at risk of breaking if Amazon ever modified their system files (and it does break if you attempt to use IMDSv2 as recommended).

So it should be provided as a string as the parameter normally expects:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#user_data
https://github.com/Coalfire-CF/terraform-aws-gitlab-prelim/blob/main/gitlab-ec2.tf#L77-L80
```
user_data = templatefile("${path.module}/userdata/ud-ansible-cli.sh", {
    aws_region = var.aws_region
    is_gov     = local.is_gov
  })
```
