### ISSUE TITLE
CM-12 Data Classification

### ISSUE THREAD

**Issue by btedder-cf** [Coalfire-CF/terraform-aws-ec2#27]
**Is your feature request related to a problem? Please describe.**
EC2 instances (and most other taggable objects) should have tags associated with CM-12 by default.  Even if we don't know the correct values, having a tag applied with a default value along with the associated lambda will ensure everything is inventoried properly. 

https://coalfire.atlassian.net/wiki/spaces/CEHOME/pages/2278260752/CM-12+and+12+1+-+Data+Classification+AWS+Only+Currently

**Describe the solution you'd like**
Tag based on the reference here.  This is fairly new and there are at least a couple different implementations.  We need to review existing implementations and decide on a standard going forward. 

**Describe alternatives you've considered**

**Additional context**

**Comment by herman-wong-cf** [comment]
#28 Closes this.
If no one defines "DataClassificationFed" in the "tags" variable, a default value of "DataClassificationFed = Direct Impact" will be used.

**Comment by herman-wong-cf** [comment]
Spoke with Thomas Kennedy, this will be set via the aws provider default_tags.
